apiVersion: apps/v1
kind: Deployment
metadata:
  name: showcase-cross-selling-page
  namespace: showcase-cross-selling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: showcase-cross-selling-page
  template:
    metadata:
      labels:
        app: showcase-cross-selling-page
    spec:
      containers:
        - name: showcase-cross-selling-page
          image: showcase-cross-selling-page:main-69e99aa-1757342145
          ports:
            - name: http-web-svc
              containerPort: 80
          env:
            - name: BACKEND_URL
              value: "http://insurance-host-agent.showcase-cross-selling.svc.cluster.local:8000"
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              port: http-web-svc
              path: /health
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 30
            httpGet:
              port: http-web-svc
              path: /health
