apiVersion: v1
kind: Service
metadata:
  name: use-case-cross-selling-showcase
  namespace: use-case-cross-selling
  labels:
    app: cross-selling-agent-showcase
spec:
  selector:
    app: use-case-cross-selling-showcase
  ports:
  - name: http
    port: 80
    targetPort: http-web-svc
    protocol: TCP
  type: ClusterIP
