apiVersion: v1
kind: Service
metadata:
  name: showcase-cross-selling-page
  namespace: showcase-cross-selling
  labels:
    app: cross-selling-agent-showcase
spec:
  selector:
    app: showcase-cross-selling-page
  ports:
  - name: http
    port: 80
    targetPort: http-web-svc
    protocol: TCP
  type: ClusterIP
